In [1]:
import numpy as np
X = np.array([.50,1.50,2.00,4.25,3.25,5.50], ndmin=2).reshape((6,1))
y = np.array([0,0,0,1,1,1])
X_mean = np.mean(X)
y_mean = np.mean(y)
n = len(X)

In [6]:
class LogisticRegression:
    b0 = 0
    b1 = 0
    def fit(self, X, y):
        upward_function = 0
        downward_function = 0
        for i in range(n):
            upward_function += (X[i]-X_mean)*(y[i]-y_mean)
            downward_function += (X[i]-X_mean)**2
        self.b1 = upward_function / downward_function
        self.b0 = y_mean - (self.b1*X_mean)
        return self.b0, self.b1
    
    def predict(self, Xi):
        z = self.b0 + (self.b1*Xi)
        sigmoid = 1/(1 + np.exp(-z))
#         y_pred = sigmoid >= 0.5
        if sigmoid >= 0.5:
            y_pred = 1
        else:
            y_pred = 0
        return sigmoid, y_pred
    
model = LogisticRegression()
print(model.fit(X,y))
model.predict(0.75)

(array([-0.2409201]), array([0.26150121]))


(array([0.48880332]), 0)

In [7]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X, y)
lr.predict([[0.75]])

c:\users\raunak\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0])