In [1]:
import numpy as np
X = np.array([.50,1.50,2.00,4.25,3.25,5.50], ndmin=2).reshape((6,1))
y = np.array([0,0,0,1,1,1])
X_mean = np.mean(X)
y_mean = np.mean(y)
n = len(X)

In [7]:
class LogisticRegression:
    b0 = 0
    b1 = 0
    sigmoid = np.array([])
    loss = np.array([])
    epoch = 10
    alpha = 0.000001
    def fit(self, X, y):
        upward_function = 0
        downward_function = 0
        for i in range(n):
            upward_function += (X[i]-X_mean)*(y[i]-y_mean)
            downward_function += (X[i]-X_mean)**2
        self.b1 = upward_function / downward_function
        self.b0 = y_mean - (self.b1*X_mean)
        return self.b0, self.b1
    
    def predict(self, Xi):
        z = self.b0 + (self.b1*Xi)
        self.sigmoid = np.append(self.sigmoid, [1/(1 + np.exp(-z))])
        return self.sigmoid
    
    def log_loss(self):
        for i in range(n):
            self.loss = np.append(self.loss, [-y[i]*np.log(self.sigmoid[i])-(1-y[i])*np.log(1-self.sigmoid[i])])
        print(self.loss)
        log_loss = np.mean(self.loss)
        return log_loss, self.sigmoid
    
    def loss_optimization(self, Xi):
        for i in range(self.epoch):
            dertivate_sigmoid = (1/n)*np.sum(self.loss*Xi)
            self.b0 = self.b0 - self.alpha*dertivate_sigmoid
            self.b1 = self.b1 - self.alpha*dertivate_sigmoid
        print('Constant : ',self.b0,'\nRegresssion Coeff : ',self.b1)
        
model = LogisticRegression()
print(model.fit(X, y))
print(model.predict(X))
print(model.log_loss())
model.loss_optimization(X)
model.log_loss()


(array([-0.2409201]), array([0.26150121]))
[0.47248545 0.53776089 0.57005666 0.70484142 0.64770326 0.76805063]
[0.63957883 0.77167297 0.84410185 0.34978244 0.43432262 0.26389962]
(0.5505597217123788, array([0.47248545, 0.53776089, 0.57005666, 0.70484142, 0.64770326,
       0.76805063]))
Constant :  [-0.24101369] 
Regresssion Coeff :  [0.26140762]
[0.63957883 0.77167297 0.84410185 0.34978244 0.43432262 0.26389962
 0.63957883 0.77167297 0.84410185 0.34978244 0.43432262 0.26389962]


(0.5505597217123789,
 array([0.47248545, 0.53776089, 0.57005666, 0.70484142, 0.64770326,
        0.76805063]))