<p>Start with data and importing libraries. 2 libraries we'll require are numpy and scikit-learn. </p>
<p>If you haven't installed them, you can install them in jupyter notebook itself :</p>
<em><b>!pip install numpy scikit-learn</b></em>

In [1]:
import numpy as np
X_data = np.array([160, 171, 182, 180, 154], ndmin=2)
X_data = X_data.reshape((5,1))
y_data = np.array([72, 76, 77, 83, 76])

In [2]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_data, y_data)
model.predict([[176]])

array([78.17022697])

Now let us start with Mean Squared Error

In [3]:
y_pred = model.predict(X_data)

In [4]:
y_pred

array([74.84846462, 77.13217623, 79.41588785, 79.00066756, 73.60280374])

In [5]:
sse = (y_data - y_pred)**2

In [6]:
sse

array([ 8.11375069,  1.28182303,  5.83651411, 15.99465999,  5.74654992])

In [7]:
mse = np.mean(sse)

In [8]:
mse

7.394659546061422

In [9]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_data, y_pred)

7.394659546061422